# Demo
# cubes: [4, 6, 8, 10]
cubes: [2, 3, 4, 5]
# Green: [2, 6]; Red: [3, 7], Blue: [4, 8], Yellow: [5, 9]
arm: "Left" # Right or Left
explore_poses: 2
search_time: 3.0

# Baxter Camera
exposure: 10
gain: 10

# Pick Offset relative to Gripper
pick_x_offset: -0.005
pick_y_offset: 0.0
pick_z_offset: 0.39

# Place Offset relative to Tower
# place_x_offset: -0.05
# place_y_offset: 0.0
# place_z_offset: 0.05
place_x_offset: 0.05
place_y_offset: 0.0
place_z_offset: -0.1

# Default Parameters
# tower_frame_: "tower" # Tower apriltag id is 1
# sleep_time_: 0.2
# find_z_offset_: -0.05
# cube_size_: 0.05
approach_z_offset: 0.05
# pull_z_offset: -0.05
